### ISSUE TITLE
[Feature Request] Script to generate input file for training forcefield.

### ISSUE THREAD

**Issue by kexul** [stefanch/sGDML#13]
Hi, Could you please share the script for generate the input file? So that users can train forcefield for any molecule. Thanks!

**Comment by stefanch** [comment]
Hi!

You can import your own datasets (see [here](http://quantum-machine.org/gdml/doc/data.html)) and use them to train your own force fields (see [here](http://quantum-machine.org/gdml/doc/training.html)).
