### ISSUE TITLE
Missing Iterative Solver

### ISSUE THREAD

**Issue by aalexmmaldonado** [stefanch/sGDML#16]
Hello,

The iterative solver was added in https://github.com/stefanch/sGDML/commit/32a489a61473bf0ac0c78bc271fa804e325aec2e here: https://github.com/stefanch/sGDML/blob/32a489a61473bf0ac0c78bc271fa804e325aec2e/sgdml/train.py#L49
but seems to be missing.

**Comment by stefanch** [comment]
Thank you for pointing that out!
This file is not included on purpose (for now). The latest release deals with this circumstance in a cleaner way.
