### ISSUE TITLE
Reproduce the interatomic distance distribution

### ISSUE THREAD

**Issue by Mo-Chen21** [stefanch/sGDML#20]
Hi, very nice work. I'm a student who is learning machine learning force field recently. I want to reproduce the figures of interatomic distance distribution shown in the paper. But I don't know how to plot this physical quantity. Is there a script in this repo? Thank you very much.

**Comment by stefanch** [comment]
Thank you for your interest in our work!

We offer a script template for running [MD simulations via ASE](http://docs.sgdml.org/applications.html#md-simulations) using sGDML models. The resulting MD trajectory is a sequence of geometries, which you can analyze (e.g. by looking at certain interatomic distances). Please refer to the [ASE documentation](https://wiki.fysik.dtu.dk/ase/index.html) for the latter task.
