### ISSUE TITLE
README.md encoding not specified in setup.py

### ISSUE THREAD

**Issue by mhellstr** [stefanch/sGDML#7]
Hello, I was unable to pip-install sgdml (Python 3.6), it gives a UnicodeDecodeError.

Changing
`with open(path.join(this_dir, 'README.md')) as f:`
to
`with open(path.join(this_dir, 'README.md'), encoding='utf8') as f:`
in setup.py solves the problem.

**Comment by stefanch** [comment]
Thank you very much!!
