### ISSUE TITLE
Exception: 'adj_set'

### ISSUE THREAD

**Issue by yyyustc** [stefanch/sGDML#9]
When I run 
'sgdml all datasets/npz/ethanol.npz 200 1000 5000'
The exception occurs.
How I can set the key 'adj_set'?
Best regard.

**Comment by stefanch** [comment]
Sorry for the inconvenience. Could you please provide more details, e.g. the strack trace for the exception? Thanks!

**Comment by yyyustc** [comment]
Sorry for  disturbing you. Here is the strack trace for the exception? Thanks!
1;30;47m STEP 1 [0m Cross-validation task creation
----------------------------------------------------------------------------------------------------
[1;37mTask properties[0m
  Energy handling: global integration constant recovery
  Symmetries:      include (sGDML)
  Compression:     not requested

[1;37;40m[INFO][0m Kernel hyper-parameter sigma was automatically set to range '2:10:100'.
[1;37;40m[INFO][0m Resuming existing hyper-parameter search in 'sgdml_cv_ethanol-
       aims.PBE.TS.light.tier.1-train200-sym'.
[1;32;40m[DONE][0m Hashing dataset(s)37m][0m Hashing dataset(s)
[1;32;40m[DONE][0m Sampling training and validation subsetsning and validation subsets

[1;30;41m[CRIT][0m Exception: 'adj_set'

**Comment by stefaanhessmann** [comment]
I had the same issue when installing the stable version. I think it could be related to the new python version 3.8.
When I build a new environment with python 3.7 everything works fine.

**Comment by yyyustc** [comment]
Thanks for your help.I changed the python version,then everything works.
By the way, could you tell me the auxiliary property  in the extended XYZ format,
Here is a segment in ethanol.xyz that you provide:

> 9
-97208.40600498248
C	0.0072	-0.5687	0.0	1.4517297437249999	6.01923561735	5.2067503058e-07
C	-1.2854	0.2499	0.0	17.9533587683	-5.1623821924	3.49002255005e-07
O	1.1304	0.3147	0.0	-4.0883694515	22.5901955842	3.30876819905e-06
H	0.0392	-1.1972	0.89	-1.141572648295	-9.7469181345	7.64734244805
H	0.0392	-1.1972	-0.89	-1.141572648295	-9.7469181345	-7.64734244805
H	-1.3175	0.8784	0.89	-2.48205465155	4.933531278999999	4.3699824457
H	-1.3175	0.8784	-0.89	-2.48205465155	4.933531278999999	-4.3699824457
H	-2.1422	-0.4239	0.0	-5.5147904611	-3.0206752464999997	-8.9092739811e-09
H	1.9857	-0.1365	0.0	-2.4392777023	-10.83820307755	-6.07213606025e-08

I want to know what the second row" -97208.40600498248 " mean,and what the fourth,fifth,sixth column mean.
Thanks!

**Comment by stefanch** [comment]
The second row contains the energy in kcal/mol and rows 4,5 and 6 contain the atomic force (x,y,z) in kcal/mol/A.
